### ISSUE TITLE
关于kanban 和 backlog 

### ISSUE THREAD

**Issue by furryrabbit** [SoftwareEngineeringPractise/Medo#5]
可以用project和issues来创建

依据backlog 把任务分解成一个个的issue， issue被创建后会自动到project的kanban上

kanban分好几列，根据issue的完成阶段把issue移动到不同的列上

@Jupiterplus

**Comment by Jupiterplus** [comment]
似乎是这样，没用过。也没时间了，你可以试试迁移到github上

**Comment by furryrabbit** [comment]
>           似乎是这样，没用过。也没时间了，你可以试试迁移到github上

你看一下project呗，我做了一点点，接下来就是任务的细分
